server {
  listen 80;
  server_name localhost;

  # Sert les fichiers Angular, redirige les URLs Angular vers index.html
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ @backend;
  }

  # Proxy vers Spring Boot pour toutes les routes inconnues
  location @backend {
    proxy_pass http://server:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
